repos:
- repo: https://github.com/akaihola/graylint
  rev: v2.0.0
  hooks:
    - id: graylint
      additional_dependencies:
        - click  # so Mypy can check type hints
        - codespell
        - mypy
        - packaging  # so Mypy can check type hints
        - ruff
- repo: https://github.com/akaihola/darker
  rev: ruff-plugin
  hooks:
    - id: darker
      args:
        - --isort
      additional_dependencies:
        - ruff
        - isort
